// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export const options = {
  vus: 10, // Nombre d'utilisateurs virtuels
  duration: '30s', // Durée du test
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    skip: "",
    skip1: "",
    test2_ok: "",
    id: ""
  }
});

export default function() {
  postman[Request]({
    name: "test1",
    id: "cc2f4618-649b-4191-9669-dd8955413eaa",
    method: "POST",
    address: "https://reqres.in/api/users",
    data: '{\n    "name": "morpheus",\n    "job": "leader"\n}',
    post(response) {
      let test1_ok = true;

      pm.test("Status code is 200", function() {
        if (pm.response.status !== 2001) {
          test1_ok = false;
        }
      });

      console.log(test1_ok);
      pm.environment.set("test1_ok", test1_ok);
    }
  });

  postman[Request]({
    name: "test2",
    id: "420972d4-27c1-4fbb-8eac-de5e5ef15aeb",
    method: "GET",
    address: "https://reqres.in/api/users/2",
    data: '{\n    "name": "morpheus",\n    "job": "leader"\n}',
    post(response) {
      let test2_ok = true;
      pm.test("Status code is 201", function() {
        pm.response.to.have.status(200);
        if (pm.response.status !== 200) {
          test2_ok = false;
        }
      });

      pm.environment.set("test2_ok", test2_ok);
    }
  });
}



export function handleSummary(data) {
  return {
    'summary.json': JSON.stringify(data), //the default data object
  };
}